name: nurturenest
services:
  nextjs:
    container_name: nextjs
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000